name: docsnap
description: "Pacote Flutter para reconhecimento de texto em imagens usando Google ML Kit."
version: 0.0.1
homepage: https://github.com/EvandroArmando/docsnap
repository: https://github.com/EvandroArmando/docsnap

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Adicione assets ou fonts se necessário
